=== stellasotirianou/car/car_rental_new2.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT car_to_rent (car*)>
<!ELEMENT car (manufacturer_brand,main_characteristics,economic_info_leasing,equipment,offer_include,extra_car_info,extra_leasing_info,ratings)>
<!ATTLIST car no ID #REQUIRED>
<!ATTLIST car polution_level (1|2|3|4|5) #IMPLIED>
<!ELEMENT manufacturer_brand (#PCDATA | model)*>
<!ELEMENT model (#PCDATA)>

<!ELEMENT main_characteristics ( (Engine,CO2_emissions,Fuel_consumption)|
                                 (Fuel_consumption,Engine,CO2_emissions)|
                                 (CO2_emissions,Fuel_consumption,Engine)|
                                 (Engine,Fuel_consumption,CO2_emissions)| 
                                 (Fuel_consumption,CO2_emissions,Engine)|
                                 (CO2_emissions,Engine,Fuel_consumption))>
<!ELEMENT Engine (#PCDATA)>
<!ELEMENT CO2_emissions (#PCDATA)>
<!ATTLIST CO2_emissions em_unit CDATA #FIXED "grCO2/km"> 
<!ATTLIST CO2_emissions mixed_cycle CDATA #IMPLIED>
<!ELEMENT Fuel_consumption (#PCDATA)>
<!ATTLIST Fuel_consumption unit_fuel CDATA #FIXED "lt/100km">
<!ATTLIST Fuel_consumption mixed_cycle CDATA #IMPLIED>

<!ELEMENT economic_info_leasing ( (monthly_leasing | (monthly_leasing,monthly_leasing)) ,payment_in_advance,retail_price,retail_price_before_taxes,detail_econ_info)>
<!ELEMENT monthly_leasing (#PCDATA)>
<!ATTLIST monthly_leasing leasing_unit CDATA "euro">
<!ATTLIST monthly_leasing without_tax (true|false) #REQUIRED>
<!ATTLIST monthly_leasing tax CDATA "24%">
<!ELEMENT payment_in_advance (amount+,descr?)>
<!ELEMENT amount (#PCDATA)>
<!ELEMENT descr (#PCDATA)>
<!ATTLIST amount without_tax (true|false) #REQUIRED>
<!ATTLIST amount tax CDATA "24%">
<!ATTLIST amount payment_unit CDATA "euro">
<!ELEMENT retail_price (#PCDATA)>
<!ATTLIST retail_price retail_unit CDATA "euro">
<!ELEMENT retail_price_before_taxes (#PCDATA)>
<!ATTLIST retail_price_before_taxes retail_bef_tax_unit CDATA "euro">
<!ELEMENT detail_econ_info (#PCDATA)>

<!ELEMENT equipment (basic_equipment,executive_equip?)>
<!ELEMENT basic_equipment (equip+)>
<!ELEMENT equip (#PCDATA)>
<!ATTLIST equip id ID #REQUIRED>
<!ELEMENT executive_equip (exec_equip+)>
<!ELEMENT exec_equip (#PCDATA)>
<!ATTLIST exec_equip id ID #REQUIRED>

<!ELEMENT offer_include (include*)>
<!ELEMENT include (#PCDATA)>

<!ELEMENT extra_car_info EMPTY>
<!ATTLIST extra_car_info mini_model_description CDATA #IMPLIED>
<!ATTLIST extra_car_info color CDATA #REQUIRED>

<!ELEMENT extra_leasing_info (category | (category,category))>
<!ELEMENT category (#PCDATA)>

<!ELEMENT ratings (rating*)>
<!ELEMENT rating (username,comment?)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT comment (#PCDATA)>
<!ATTLIST rating stars (1|2|3|4|5) #REQUIRED>

=== stellasotirianou/car/car_rental_new2.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE car_to_rent SYSTEM "car_rental_new2.dtd">

<car_to_rent>
    <car no="No.1" polution_level="2">
        <manufacturer_brand>
            Renault 
            <model>CLIO V</model>
        </manufacturer_brand>
        <main_characteristics>
            <Engine>1.5 dci 85hp</Engine>
            <CO2_emissions em_unit="grCO2/km">101</CO2_emissions>
            <Fuel_consumption unit_fuel="lt/100km">3,6 - 3,8</Fuel_consumption>
        </main_characteristics>
       <economic_info_leasing>
            <monthly_leasing leasing_unit="euro" without_tax="true">143€</monthly_leasing>
            <monthly_leasing leasing_unit="euro" without_tax="false" tax="24%">177€</monthly_leasing>
            <payment_in_advance>
               <amount without_tax="false" tax="24%" payment_unit="euro">3200€</amount>
               <amount without_tax="true" payment_unit="euro">3968€</amount>
               <descr>Λαμβάνεται ως πρώτο μίσθωμα</descr>
            </payment_in_advance>
            <retail_price retail_unit="euro">15.592€</retail_price>
            <retail_price_before_taxes  retail_bef_tax_unit="euro">11.921€</retail_price_before_taxes>
            <detail_econ_info>Η τιμή ισχύει για μίσθωση 48 μηνών και καλύπτει 20.000 χλμ. τον χρόνο.</detail_econ_info>
        </economic_info_leasing>
        <equipment>
            <basic_equipment>
                <equip id="e1.1">ABS με EBV και AFU</equip>
                <equip id="e1.2">Ηλεκτρονικός έλεγχος ευστάθειας (ESC) και ASR</equip>
                <equip id="e1.3">Hill Start Assist (σύστημα υποβοήθησης εκκίνησης σε οδόστρωμα με κλίση)</equip>
                <equip id="e1.4">Μετωπικοί αερόσακοι οδηγού-συνοδηγού </equip>
                <equip id="e1.5">Αερόσακοι πλευρικοί εμπρός  για την προστασία του κεφαλιού και του θώρακα</equip>
                <equip id="e1.6">Αερόσακοι τύπου κουρτίνας εμπρός/πίσω</equip>
                <equip id="e1.7">Αυτόματο σύστημα πέδησης έκτακτης ανάγκης με ανίχνευση πεζών και δικύκλων (AEB)</equip>
                <equip id="e1.8">Cruise Control με Speed limiter και χειριστήρια στο τιμόνι</equip>
                <equip id="e1.9">Αναγνώριση πινακίδων οδικής κυκλοφορίας (TSR) </equip>
                <equip id="e1.10">Σύστημα υποβοήθησης διατήρησης λωρίδας (LKA) &amp; Προειδοποίηση Αλλαγής Λωρίδας Κυκλοφορίας (LDW)</equip>
                <equip id="e1.11">Πίνακας οργάνων με εγχρωμη οθόνη 4,2”</equip>
                <equip id="e1.12">Air Condition με φίλτρο γύρης και μικροσωματιδίων</equip>
                <equip id="e1.13">Τιμόνι ρυθμιζόμενο σε ύψος και μήκος , με ηλεκτρική υποβοήθηση</equip>
                <equip id="e1.14">Κάθισμα οδηγού ρυθμιζόμενο σε ύψος</equip>
                <equip id="e1.15">Εμπρός προσκέφαλα ρυθμιζόμενα καθ'ύψος</equip>
                <equip id="e1.16">3 προσκέφαλα πίσω, ρυθμιζόμενα σε ύψος</equip>
                <equip id="e1.17">Διαιρούμενο πίσω κάθισμα 1/3-2/3</equip>
                <equip id="e1.18">Ηλεκτρικά παράθυρα εμπρός &amp; Παράθυρο οδηγού συνεχούς λειτουργίας</equip>
                <equip id="e1.19">Υπολογιστής ταξιδίου</equip>
                <equip id="e1.20">Διακόπτης ECO</equip>
                <equip id="e1.21">Ηλεκτρικά ρυθμιζόμενοι &amp; θερμαινόμενοι καθρέφτες</equip>
                <equip id="e1.22">Κεντρικό κλείδωμα με τηλεχειρισμό (Foldable key )</equip>
                <equip id="e1.23">Φώτα ημέρας LED</equip>
                <equip id="e1.24">Τροχοί 15'' IREMIA</equip>
            </basic_equipment>
        </equipment>
        <offer_include>
           <include>- Συντήρηση και επισκευή αυτοκινήτου</include>
           <include>- Πλήρη ασφαλιστική κάλυψη (ίδιες ζημιές με απαλλαγή - 24ωρη οδική βοήθεια)</include>
           <include>- Τέλη κυκλοφορίας</include>
           <include>- Αντικατάσταση αυτοκινήτου</include>
           <include>- Δυνατότητα χρήσης προσωρινού αυτοκινήτου</include>
           <include>- Αλλαγή ελαστικών</include>
        </offer_include>
        <extra_car_info color="Λευκό" mini_model_description="1.5 dci 85hp AUTHENTIC MANUAL"></extra_car_info>
        <extra_leasing_info>
            <category>private</category>
        </extra_leasing_info>
        <ratings>
            <rating stars="4">
                <username>kostaspapadopoulos</username>
                <comment>Έμεινα αρκετά ευχαριστημένος</comment>
            </rating>
            <rating stars="3">
                <username>mariapd</username>
            </rating>
        </ratings>
    </car>
    <car no="No.2" polution_level="1">
        <manufacturer_brand>
            Mini Cooper
            <model>Mini Countryman</model>
        </manufacturer_brand>
         <main_characteristics>
            <Engine>Euro 6DG Βενζίνη</Engine>
            <CO2_emissions em_unit="grCO2/km">122</CO2_emissions>
            <Fuel_consumption unit_fuel="lt/100km">5,4</Fuel_consumption>
        </main_characteristics>
        <economic_info_leasing>
            <monthly_leasing leasing_unit="euro" without_tax="true">239€</monthly_leasing>
            <monthly_leasing leasing_unit="euro" without_tax="false" tax="24%">296€</monthly_leasing>
            <payment_in_advance>
               <amount without_tax="false" tax="24%" payment_unit="euro">5.700€</amount>
               <amount without_tax="true" payment_unit="euro">7.068€</amount>
            </payment_in_advance>
            <retail_price retail_unit="euro">28.176€</retail_price>
            <retail_price_before_taxes  retail_bef_tax_unit="euro">19.898€</retail_price_before_taxes>
            <detail_econ_info> Η τιμή ισχύει για μίσθωση 48 μηνών και καλύπτει 18.000 χλμ. τον χρόνο.</detail_econ_info>
        </economic_info_leasing>
         <equipment>
            <basic_equipment>
                <equip id="e2.1">Δυναμικός Έλεγχος Ευστάθειας</equip>
                <equip id="e2.2">Προειδοποίηση πρόσκρουσης</equip>
                <equip id="e2.3">Εκκίνηση χωρίς χρήση κλειδιού</equip>
                <equip id="e2.4">Σπορ δερμάτινο πολυλειτουργικό τιμόνι </equip>
                <equip id="e2.5"> Servotronic</equip>
                <equip id="e2.6">Υποβραχιόνιο εμπρός</equip>
                <equip id="e2.7">Έγχρωμη κεντρική οθόνη αφής 6,5’’ Visual Boost</equip>
                <equip id="e2.8">Υπολογιστής ταξιδίου</equip>
                <equip id="e2.9"> 8 προγραμματιζόμενα πλήκτρα αφής, άμεσης πρόσβασης λειτουργιών &amp; πολύ-χειριστήριο iDrive</equip>
                <equip id="e2.10">Ηχοσύστημα με 6 ηχεία</equip>
                <equip id="e2.11">Σύστημα ανοικτής ακρόασης Bluetooth &amp; θύρα USB</equip>
                <equip id="e2.12">Κλήση έκτακτης ανάγκης / Teleservices</equip>
                <equip id="e2.13">Ηλεκτρικό χειρόφρενο</equip>
                <equip id="e2.14">Αισθητήρας βροχής και φώτων</equip>
                <equip id="e2.15">Πίσω φώτα LED</equip>
                <equip id="e2.16">Ένδειξη πίεσης ελαστικών</equip>
                <equip id="e2.17">Κιτ επισκευής ελαστικών</equip>
                <equip id="e2.18">Επένδυση καθισμάτων με ύφασμα</equip>
                <equip id="e2.19">Αναδιπλούμενο πίσω κάθισμα (40:20:40</equip>
                <equip id="e2.20">Στήριξη παιδικού καθίσματος Isofix εμπρός</equip>
                <equip id="e2.21">Λευκά φλας</equip>
                <equip id="e2.22">Κάθισμα συνοδηγού ρυθμιζόμενο καθ΄ ύψος</equip>
                <equip id="e2.23">Βελούδινα ταπέτα</equip>
            </basic_equipment>
            <executive_equip>
                <exec_equip id="ex2.1">Αυτόματο κιβώτιο 7 σχέσεων</exec_equip>
                <exec_equip id="ex2.2">Μεταλλικό χρώμα</exec_equip>
                <exec_equip id="ex2.3">Ζάντες ελαφρού κράματος 17’’</exec_equip>
                <exec_equip id="ex2.4">Ράγες οροφής</exec_equip>
                <exec_equip id="ex2.5">Αυτόματος διζωνικός κλιματισμός</exec_equip>
                <exec_equip id="ex2.6">Αισθητήρες παρκαρίσματος πίσω</exec_equip>
                <exec_equip id="ex2.7">Πακέτο φωτισμού</exec_equip>
                <exec_equip id="ex2.8">Προβολείς ομίχλης LED</exec_equip>
                <exec_equip id="ex2.9">Σύστημα πλοήγησης ΜΙΝΙ</exec_equip>
                <exec_equip id="ex2.10">Apple CarPlay</exec_equip>
                <exec_equip id="ex2.11">Χρώμα οροφής σε μαύρο, ασημί, λευκό ή στο χρώμα του αμαξώματος</exec_equip>
            </executive_equip>
        </equipment>
        <offer_include>
           <include>- Συντήρηση και επισκευή αυτοκινήτου</include>
           <include>- Πλήρη ασφαλιστική κάλυψη (ίδιες ζημιές με απαλλαγή - 24ωρη οδική βοήθεια)</include>
           <include>- Τέλη κυκλοφορίας</include>
           <include>- Αντικατάσταση αυτοκινήτου</include>
           <include>- Δυνατότητα χρήσης προσωρινού αυτοκινήτου</include>
           <include>- Αλλαγή ελαστικών</include>
        </offer_include>
        <extra_car_info color="Μαύρο" mini_model_description="Executive AUTO"></extra_car_info>
        <extra_leasing_info>
            <category>private</category>
            <category>company</category>
        </extra_leasing_info>
        <ratings>
            <rating stars="4">
                <username>chris_p</username>
            </rating>
            <rating stars="5">
                <username>stella_sot</username>
                <comment>Ωραίο design, καλή απόδωση.</comment>
            </rating>
        </ratings>
    </car>
    <car no="No.3" polution_level="4">
        <manufacturer_brand >
            Toyota
            <model>Aygo Auto</model>
        </manufacturer_brand>
         <main_characteristics>
            <Engine>Petrol/Euro 6.2</Engine>
            <CO2_emissions em_unit="grCO2/km">95</CO2_emissions>
            <Fuel_consumption unit_fuel="lt/100km">4,2</Fuel_consumption>
